<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
  </PropertyGroup>
  <!--Package versions-->
  <PropertyGroup>
    <Foo12dd1570PackageVersion>
    </Foo12dd1570PackageVersion>
    <Bar12dd1570PackageVersion>
    </Bar12dd1570PackageVersion>
    <PinnedFoo12dd1570PackageVersion>
    </PinnedFoo12dd1570PackageVersion>
    <PinnedBar12dd1570PackageVersion>
    </PinnedBar12dd1570PackageVersion>
  </PropertyGroup>
</Project>
